module.exports = {
    Admin: require('./Admin.model'),
    Employee: require('./Employee.model'),
    PropertyType:require('./PropertyType.model'),
    PropertyConditions:require('./PropertyConditions.model'),
    OwnershipType:require('./OwnershipType.model'),
    Project:require('./Project.model'),
    ProjectImage:require('./ProjectImage.model'),
    LeadStatus:require('./LeadStatus.model'),
    LeadSource:require('./LeadSource.model'),
    LocationPreference:require('./LocationPreference.model'),
    Timeline:require('./Timeline.model'),
    LeadLabel:require('./LeadLabel.model'),
    Lead:require('./Lead.model'),
    AssignProject:require('./AssignProject.model'),
    Designation:require('./Designation.model'),
    Remark:require('./Remark.model'),
    AssignLead:require('./AssignLead.model'),
    LeadTimeline:require('./LeadTimeline.model'),
    ShareLead:require('./ShareLead.model'),
    Attendance:require('./Attendance.model'),
    Attachment:require('./Attachment.model'),
    Calendar:require('./Calendar.model'),
    LeaveRequest:require('./LeaveRequest.model'),
    Message:require('./Message.model'),
    Salaries:require('./Salaries.model'),
    LocationTruck:require('./LocationTruck.model'),
    Notification:require('./Notification.model'),
    AdminSetting:require('./AdminSetting.model'),
    Source:require('./source.model'),
    Asset:require('./asset.model'),
    Expense: require('./Expense.model'),
};
